# Generated by Django 3.2.12 on 2022-08-16 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('albums', '0001_initial'),
        ('bands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bands.band'),
        ),
        migrations.AddField(
            model_name='song',
            name='band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.album'),
        ),
    ]
