# Generated by Django 3.2.12 on 2022-08-16 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('middle_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('genre', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
                ('role', models.CharField(max_length=15)),
            ],
        ),
    ]
