# Generated by Django 3.2.12 on 2022-08-31 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='band',
            old_name='album',
            new_name='song',
        ),
    ]
